#
# Production server with UWSGI configured to run on port 8080
# Please use the accompanying make targets to run rather than
# calling fig commands directly on this file.

smtp:
  image: catatnight/postfix
  hostname: postfix
  environment:
    # You could change this to something more suitable
    - maildomain=kartoza.com
    - smtp_user=noreply:docker

db:
  image: kartoza/postgis
  volumes:
    - ./pg/postgres_data:/var/lib/postgresql
  environment:
    - USERNAME=docker
    - PASS=docker
  ports:
    - "6543:5432"

dbbackup:
  image: kartoza/pg-backup
  hostname: pg-backups
  volumes:
    - ./pg/dbbackup/backups:/backups
  links:
    - db:db
  environment:
    - DUMPPREFIX=realtime
    # These are all defaults anyway, but setting explicitly in
    # case we ever want to ever use different credentials
    - PGUSER=docker
    - PGPASSWORD=docker
    - PGPORT=5432
    - PGHOST=db
    - PGDATABASE=gis

uwsgi:
  build: docker-prod
  hostname: uwsgi
  environment:
    - DATABASE_NAME=gis
    - DATABASE_USERNAME=docker
    - DATABASE_PASSWORD=docker
    - DATABASE_HOST=db
    - DJANGO_SETTINGS_MODULE=core.settings.prod_docker
    - VIRTUAL_HOST=users.inasafe.org
    - VIRTUAL_PORT=8080
  volumes:
    - ../django_project:/home/web/django_project
    - ./static:/home/web/static
    - ./media:/home/web/media
    - ./reports:/home/web/reports
    - ./logs:/var/log/
  links:
    - smtp:smtp
    - db:db
    - dbbackup:dbbackup

web:
  image: nginx
  hostname: nginx
  volumes:
    - ./sites-enabled:/etc/nginx/conf.d:ro
    # I dont use volumes_from as I want to use the ro modifier
    - ./static:/home/web/static:ro
    - ./media:/home/web/media:ro
    - ./logs:/var/log/nginx
  links:
    - uwsgi:uwsgi
  ports:
    - "61100:8080"
